# Default values for rollout-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 10
port: 80
image:
  repository: ghcr.io/dhpup/guestbook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.40

service:
  type: NodePort