apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Chart.Name }}-success-rate
spec:
  args:
    - name: service
    - name: namespace
  metrics:
    - name: integration-tests
      failureLimit: 3
      interval: 5s
      count: 4
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: load-tester
                    image: argoproj/load-tester:latest
                    command: [sh, -xec]
                    args:
                      - |
                        wrk -t1 -c1 -d5 -s report.lua http://{{`{{args.service}}.{{args.namespace}}`}}.svc.cluster.local
                        jq -e '.errors_ratio <= 0.05' report.json
                restartPolicy: Never
            backoffLimit: 0