apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Chart.Name }}-success-rate
spec:
  args:
    - name: service
    - name: namespace
  metrics:
    - name: integration-tests
      failureLimit: 3
      interval: 5s
      count: 4
      provider:
        job:
          spec:
            template:
              spec:
                containers:
                  - name: load-tester
                    command: [sh, -xec]
                    image: blaaake/vegeta
                    args:
                      - |
                        echo 'GET http://{{`{{args.service}}.{{args.namespace}}`}}.svc.cluster.local' | \
                        vegeta attack -rate=10 -duration=30s | tee results.bin | vegeta report -type json > results.json && \ 
                        cat results.json && jq -e '.success >= 0.95' results.json
                restartPolicy: Never
            backoffLimit: 0