apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-canary"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11111
      targetPort: http
      protocol: TCP
      name: http