apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-stable"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 22222
      targetPort: http
      protocol: TCP
      name: http